config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'geocoder/localposittion'
  devise_for :users, controllers: {
    registrations:       'users/registrations',
    omniauth_callbacks:  'users/omniauth_callbacks'
  }
  #ActionCable
  mount ActionCable.server => '/cable'
  
  #Chat
  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]
  resources :users, only: [:index]
  root to: 'users#index'
  
  #Omniauth login with facebook and google
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    
  def index
    @chat_rooms = ChatRoom.all
  end


  def new
    @chat_room = ChatRoom.new
  end
    
  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end


  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end
    
  def destroy
    @chat_room = ChatRoom.find(params[:id])
    @chat_room.destroy
    redirect_to chat_rooms_path
  end
    
  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_chat_room.html.erb
<% @chat_rooms.each do |chatroom|%>
  <div class='list-group'>
    <div class='row' style='height:60px'>
      <div class= 'col-md-8'>
        <tr>
          <td><%= link_to "#{chatroom.title.capitalize}", chat_room_path(chatroom), class: 'list-group-item list-group-item-primary' %></td>
        </tr>
      </div>
      <div class='col-md-1'>
        <%= link_to chat_room_path(chatroom), method: :delete, class:'btn btn-danger' do %>
          <%= fa_icon "trash" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>
<div>
  <p class="lead "><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>
  <p class='lead'><%= link_to 'Volver al index', root_path, class:'btn btn-primary' %></p>
</div>
<div class='row'>
  <div class='col-md-6'>
    <div class='container-fluid'>
      <%= render 'chat_room' %>
    </div>
  </div>
</div>

app/views/chat_rooms/new.html.erb
<div class='container-fluid'>
  <h1>Add chat room</h1>
  <div class='row'>
    <div class='col-md-4' >
      <%= form_for @chat_room do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        </div>

        <%= f.submit "Add!", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/chat_rooms/show.html.erb
<div class='container-fluid-chat'>
  <h1><%= @chat_room.title.capitalize  %></h1>
  <div class='chat-btn-back'>
    <%= link_to 'Volver a chats', chat_rooms_path, class:'btn btn-primary'%>
  </div>
<div class='block-chat'>
  <div class='block-messages' id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
  </div>

  <div class='chat-container-input'>
    <div class='chat-input'>
      <div class="form-group">
        <%= form_for(@message, url: '#', remote: true) do |f| %>
          <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
            <%= f.label :'Escribe tu mensaje aquí', class: 'chat-label-message' %>
            <%= f.text_area :body, class: 'form-control' %>
            <small class="text-muted">From 2 to 1000 characters</small>
      </div>

        <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
        <% end %>
    </div>
  </div>
</div>